services:
  bricedjego:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bricedjego
    restart: always
    ports:
      - "8080:80"
    networks:
      - agpdp

networks:
  agpdp:
    external: true